<?xml version="1.0" encoding="UTF-8"?><magicdraw><comment classType="Comment" humanType="Comment" icon="index_files/icon_comment_841774062.jpg" id="_10_5_622020d_1132928310292_159934_6710" refElementId="_10_5_622020d_1132928310292_159934_6710"><annotatedElement humanName="Annotated Element" mode="s,e"><class classType="Class" humanType="Class" icon="index_files/icon_class_555864569.jpg" name="TimeoutException" refElementId="_10_5_622020d_1132928310292_266470_6708" refid="_10_5_622020d_1132928310292_266470_6708"/></annotatedElement><body humanName="Body" mode="s,e">Exception thrown when a blocking operation times out.  Blocking
operations for which a timeout is specified need a means to
indicate that the timeout has occurred. For many such operations it
is possible to return a value that indicates timeout; when that is
not possible or desirable then &lt;tt&gt;TimeoutException&lt;/tt&gt; should be
declared and thrown.

@since 1.5
@author Doug Lea
</body><documentation humanName="Documentation"/><owner classType="Class" humanName="Owner" humanType="Class" icon="index_files/icon_class_555864569.jpg" mode="s,e" name="TimeoutException" refElementId="_10_5_622020d_1132928310292_266470_6708" refid="_10_5_622020d_1132928310292_266470_6708"/><owningElement classType="Class" humanName="Owning Element" humanType="Class" icon="index_files/icon_class_555864569.jpg" name="TimeoutException" refElementId="_10_5_622020d_1132928310292_266470_6708" refid="_10_5_622020d_1132928310292_266470_6708"/><TO_DO humanName="To Do" mode="s,e"/></comment></magicdraw>