<?xml version="1.0" encoding="UTF-8"?><magicdraw><comment classType="Comment" humanType="Comment" icon="index_files/icon_comment_2051026490.jpg" id="_10_5_622020d_1132928309040_111911_5714"><annotatedElement humanName="Annotated Element" mode="s,e"><class classType="Class" humanType="Class" icon="index_files/icon_class_1555793073.jpg" name="ConnectIOException" refid="_9_5_f720368_1110473546674_897103_8221"/></annotatedElement><body humanName="Body" mode="s,e">A &lt;code&gt;ConnectIOException&lt;/code&gt; is thrown if an
&lt;code&gt;IOException&lt;/code&gt; occurs while making a connection
to the remote host for a remote method call.

@version 1.12, 12/19/03
@author  Ann Wollrath
@since   JDK1.1
</body><documentation humanName="Documentation"/><owner classType="Class" humanName="Owner" humanType="Class" icon="index_files/icon_class_1555793073.jpg" mode="s,e" name="ConnectIOException" refid="_9_5_f720368_1110473546674_897103_8221"/><owningElement classType="Class" humanName="Owning Element" humanType="Class" icon="index_files/icon_class_1555793073.jpg" name="ConnectIOException" refid="_9_5_f720368_1110473546674_897103_8221"/><TO_DO humanName="To Do" mode="s,e"/></comment></magicdraw>