<?xml version="1.0" encoding="UTF-8"?><magicdraw><comment classType="Comment" humanType="Comment" icon="index_files/icon_comment_841774062.jpg" id="_10_5_622020d_1132928314979_863316_9448" refElementId="_10_5_622020d_1132928314979_863316_9448"><annotatedElement humanName="Annotated Element" mode="s,e"><class classType="Class" humanType="Class" icon="index_files/icon_class_555864569.jpg" name="InvalidRelationIdException" refElementId="_10_5_622020d_1132928314979_675677_9446" refid="_10_5_622020d_1132928314979_675677_9446"/></annotatedElement><body humanName="Body" mode="s,e">This exception is raised when relation id provided for a relation is already
used.

@since 1.5
</body><documentation humanName="Documentation"/><owner classType="Class" humanName="Owner" humanType="Class" icon="index_files/icon_class_555864569.jpg" mode="s,e" name="InvalidRelationIdException" refElementId="_10_5_622020d_1132928314979_675677_9446" refid="_10_5_622020d_1132928314979_675677_9446"/><owningElement classType="Class" humanName="Owning Element" humanType="Class" icon="index_files/icon_class_555864569.jpg" name="InvalidRelationIdException" refElementId="_10_5_622020d_1132928314979_675677_9446" refid="_10_5_622020d_1132928314979_675677_9446"/><TO_DO humanName="To Do" mode="s,e"/></comment></magicdraw>