<?xml version="1.0" encoding="UTF-8"?><magicdraw><comment classType="Comment" humanType="Comment" icon="index_files/icon_comment_841774062.jpg" id="_10_5_622020d_1132928310312_782025_6743" refElementId="_10_5_622020d_1132928310312_782025_6743"><annotatedElement humanName="Annotated Element" mode="s,e"><class classType="Class" humanType="Class" icon="index_files/icon_class_555864569.jpg" name="ErrorManager" refElementId="_9_5_f720368_1110473546690_439634_8719" refid="_9_5_f720368_1110473546690_439634_8719"/></annotatedElement><body humanName="Body" mode="s,e">ErrorManager objects can be attached to Handlers to process
any error that occur on a Handler during Logging.
&lt;p&gt;
When processing logging output, if a Handler encounters problems
then rather than throwing an Exception back to the issuer of
the logging call (who is unlikely to be interested) the Handler
should call its associated ErrorManager.
</body><documentation humanName="Documentation"/><owner classType="Class" humanName="Owner" humanType="Class" icon="index_files/icon_class_555864569.jpg" mode="s,e" name="ErrorManager" refElementId="_9_5_f720368_1110473546690_439634_8719" refid="_9_5_f720368_1110473546690_439634_8719"/><owningElement classType="Class" humanName="Owning Element" humanType="Class" icon="index_files/icon_class_555864569.jpg" name="ErrorManager" refElementId="_9_5_f720368_1110473546690_439634_8719" refid="_9_5_f720368_1110473546690_439634_8719"/><TO_DO humanName="To Do" mode="s,e"/></comment></magicdraw>